### ISSUE TITLE
Previous NR is missing in Namex

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1015]
##### _**Detailed Description**_
New Corporation (Foreign) - EP Assumed Name submitted via NRO (staff role) is missing the Previous NR field in Namex. I supplied NR 3835768, and this shows in the additional info, but not in Previous NR.

Example NR in Test: NR 0611259

**Comment by katiemcgoff** [comment]
This is not a bug - in this case, the NR linked as the Previous NR (NR 3835768) does not exist in the TEST namex database. I can see that the record ID from NRO does come through, but it can't be converted to an NR xxxxxxx number.

If you want to retry this, you could find an existing NR in the TEST environment and use that NR as the previous NR in NRO, and then ensure that the data travels the entire path from NRO to Namex. I am confident it will, though, since that NRO record ID does come through (see screenshot).

@JohnamLane I'll leave this with you to verify not a bug and close, or come back to me with questions.

![2018-10-16_11-39-16](https://user-images.githubusercontent.com/3835295/47039355-9bf99900-d138-11e8-9373-496c0b037463.png)

**Comment by JohnamLane** [comment]
@katiemcgoff You're right! 3239003 is a fresh one in Test and it populates previous NR # as expected. Marking as invalid and closing.
