### ISSUE TITLE
Production has names in the COMPLETED state

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1046]
##### _**Detailed Description**_
During prod testing I noticed that there are names with the state of COMPLETED. This state is normally converted to approve/rejected/conditional by the extractor

##### _**Acceptance Criteria**_
No names in production showing the status of completed.

**Comment by katiemcgoff** [comment]
Done. Ran the following statements on prod db (in order) to make changes. 49 remaining COMPLETED NRs due to bad name data (all NE names, or no names at all):

update requests set state_cd='APPROVED' where id in (
select requests.id from requests join names on nr_id=requests.id where state_cd='COMPLETED' and state='APPROVED' );
_347,353 rows updated_

update requests set state_cd='CONDITIONAL' where id in (
select requests.id from requests join names on nr_id=requests.id where state_cd='COMPLETED' and state='CONDITION' );
_25,972 rows updated_

update requests set state_cd='REJECTED' where id in (
select requests.id from requests join names on nr_id=requests.id where state_cd='COMPLETED' and state='REJECTED' );
_57,052 rows updated_
