### ISSUE TITLE
Create a way to send information to a third party from name X

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1085]
##### _**Detailed Description**_
We will need to verify the information that needs to be sent.

**Comment by ericminio** [comment]
From our meeting with users I keep the following:

To send info, one option they currently have is to copy/paste info from namex screen into a Word document, then remove info they don't want to send like internal comments, change style and layout like expiry date in bold, attach this document in an email and send the email.

We have several options to try to improve their life.

1. revamp the screen so that the copy and paste operation does not require any modification from them. That means change the layout and styles of the page. The good news is that this revamp is already scheduled for next week. Including this copy/paste concern in the revamp seems a cheap way of addressing the need.

2. have a send button that does it all, from creating a pdf to sending an email with the pdf attached.

3. anything in between

**Comment by Kaineatthelab** [comment]
Thank you, this needs more discovery. I will assign to Scott and Julia to understand more of the needs/research and make some mock ups.

**Comment by LJTrent** [comment]
Same request as formatting and emailing NWPTA info.
