### ISSUE TITLE
Missing Corporation in Corp Details

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1162]
##### _**Detailed Description**_
The conflict list is displaying a corporation name that it cannot load the corp details for.  The message for corp info is displayed.  The solr core has the corporation and the corp data is in the cprd database as expected.   

##### _**Acceptance Criteria**_
When the user selects a conflict in the list that is a corporation the system should display the corp details.

Sample in prod: Here is the solr doc: {
       "name":"BRM HOLDINGS LTD.",
       "name_copy":"BRM HOLDINGS LTD.",
       "name_with_synonyms":"BRM HOLDINGS LTD.",
       "name_compressed":"BRM HOLDINGS LTD.",
       "state_type_cd":"ACT",
       "id":"0959209",
       "source":"CORP",
       "version":1615214105636896776},

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by perkinss** [comment]
I'm not able to reproduce this.  The name given above has no problem in the test database.
Can we obtain any other information available from the production app, such as the network response?

For example something like this from the chrome developer tools?

<img width="958" alt="screen shot 2018-11-13 at 3 07 59 pm" src="https://user-images.githubusercontent.com/405204/48449090-06145680-e756-11e8-9818-8e8f15fdc9b7.png">

**Comment by perkinss** [comment]
Colin API Log error: [SQL: "select addr_line_1, ADDR_LINE_2, ADDR_LINE_3, city, province, country_typ_cd, postal_cd from bc_registries.address_vw where addr_id= 'None';"]

**Comment by perkinss** [comment]
WEIRD.  That same corp is now returning the data in prod.

**Comment by perkinss** [comment]
Need to put this bug on hold till we can reproduce it ...

**Comment by perkinss** [comment]
My understanding at this point is that this only occurs very sporadically, even for the same corporation,

The corporation given has 3 active addresses in the view.  One of them has a null delivery_addr_id.  When the corporation addresses are called we only use the first of the ones returned.  The query does not return the data in any particular order, so sometimes we end up with the address with the null delivery_addr_id in the first row, and then we try to retrieve the address using the null id, which breaks the whole api call.

**Comment by perkinss** [comment]
Solutions:

1.  Change the colin api query so it orders the returned data by delivery_addr_id, and puts nulls last.  
   * This would help in cases where xpro corporations have more than one office given, and one without a null delivery address
   * Or where BC addresses have more than 2 offices, and at least two have valid (non-null) delivery address ids
2.  Change the db view so that it does not list the offices with null delivery address ids.  This needs more investigation to determine all aspects that this change would affect.  
3.  Change the colin api query to use something other than the delivery address id to fetch the address details.
    
There has also been discussion around changing the display of corporate office addresses.  If we move in this direction someone with permissions on the repository should create a new ticket to investigate the business needs around displaying corporate addresses in further detail.  For example, are there any cases where there is no delivery address and only a mailing address?  Do the examiners need to see other addresses for the xpro corporations?  Do they need to see all the addresses for any reason?  Do they want to see the email address for offices without delivery addresses?

**Comment by perkinss** [comment]
From the business side, "Xtrapro companies provide us with a Head Office Mailing and a Head Office Delivery Address.  I don’t know where the examiners are seeing 5 addresses.  The most we would have is 4 addresses.  One Head Office Mailing Address. One Head Office Delivery address. If the Head Office address is outside of B.C. they would also provide us with an Attorney that would also have a Mailing Address and Delivery Address. " 

"B.C. Companies have a Registered Office Mailing Address, Registered Office Delivery Address, Records Office Mailing Address, and a Registered Office Delivery Address. "

"A B.C. Society has a Registered Office Mailing Address and a Registered Office Delivery Address.  "

"Extraprovincial Non-Share Corporation have to have a Head Office Mailing Address and a Head Office Delivery Address.  If the Head Office Address is outside of B.C. they must have an Attorney on file.  The Attorney will have a Mailing and Delivery Address. "

So there would never be more than 4 for any corporation.  
Currently we don't get the attorney addresses, just their names, for display in the corporation info pane.

**Comment by LJTrent** [comment]
Addressed by another ticket on the entity board.
