### ISSUE TITLE
Update SOLR API

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#728]
Will probably need to invent a new symbol for solr markup, such as "@".
We also need to use the latest query which I gave Walter on Slack.
As well we want to put a plus sign in front of the first word by default as we think in most cases the first word will be the distinctive.  Once it goes to a manual search we will want the user to be able to take out the plus sign on the first word so not sure if this part should be done on the front-end instead?

Acceptance Criteria:
- As a user, I need to be able to exclude a word from checking synonyms, without excluding the whole phrase from synonym checking.

ex: Arrow Construction, where both "Arrow" and "Construction" have synonyms
- we want to exclude Arrow from using synonyms but still check the synonyms for "construction".

**Comment by WalterMoar** [comment]
https://namex-solr-test.pathfinder.gov.bc.ca/solr/names/select?defType=edismax&fq=name_copy:RED&indent=on&mm=75%&q=RED CLEANING SERVICES LTD.&qf=name&wt=json

this is the one that will get passed from the front-end with the *RED CLEANING SERVICES LTD so that Red will not be substituted with the synonyms.  the clause &fq=name_copy:RED is what says only give me back he ones with RED.

**Comment by WalterMoar** [comment]
Decided to go with @ for the symbol - * is being used by Solr already.

**Comment by LJTrent** [comment]
@WalterMoar 

All symbols with quotes seem to be working except @"LIVING ATMOSPHERES" INC.  You get a  Request failed with status code 500.  It appears to be a real bug.

**Comment by WalterMoar** [comment]
Fixed: the new query string was not being escaped.

**Comment by WalterMoar** [comment]
Deployed to dev. Will wait and let this piggyback on another deploy to test.

**Comment by WalterMoar** [comment]
I think this went to test yesterday at noon.
